spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: false
  data:
    mongodb:
      database: email
      uri: mongodb://localhost:27017/${spring.data.mongodb.database}


aws:
  bucket:
    name: testokay
  region: eu-central-1


mongock:
  change-logs-scan-package:
    - com.magg.files

grpc:
  server:
    maxInboundMessageSize: 15MB